USE [DShield]
GO
-- =============================================
-- Title:       Reference - Protocols
-- Author:		Curtis Dibble
-- Date:		12/14/2024
-- Schema:		Reference
-- Type:		Table
-- Description:
--  Store Quick Lookup of IP Protocol Info (All)
-- =============================================
CREATE TABLE [Reference].[Protocols] (
    [Number] INT PRIMARY KEY,
    [Name] VARCHAR(255) NULL,
    [Keyword] VARCHAR(31) NOT NULL
    CONSTRAINT UQ_Reference_Protocols_Number_Keyword UNIQUE ([Number], [Keyword]),
);

GO

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE ON OBJECT::[Reference].[Protocols] TO [ReferenceManager]
GO

GRANT REFERENCES, SELECT ON OBJECT::[Reference].[Protocols] TO [ReferenceReader]
GO 

-- =============================================
-- Title:       Preload - Protocols
-- Author:		Curtis Dibble
-- Date:		12/14/2024
-- Schema:		Reference
-- Type:		Data
-- Description:
--  Preload the Protocols table (All)
-- =============================================
INSERT INTO [Reference].[Protocols] 
	([Number], [Name], [Keyword]) 
VALUES 
    (0, 'IPv6 Hop-by-Hop Option', 'HOPOPT'),
    (1, 'Internet Control Message Protocol', 'ICMP'),
    (2, 'Internet Group Management Protocol', 'IGMP'),
    (3, 'Gateway-to-Gateway Protocol', 'GGP'),
    (4, 'IP in IP (encapsulation)', 'IP-in-IP'),
    (5, 'Internet Stream Protocol', 'ST'),
    (6, 'Transmission Control Protocol', 'TCP'),
    (7, 'Core-based trees', 'CBT'),
    (8, 'Exterior Gateway Protocol', 'EGP'),
    (9, 'Interior gateway protocol (any private interior gateway, for example Ciscos IGRP)', 'IGP'),
    (10, 'BBN RCC Monitoring', 'BBN-RCC-MON'),
    (11, 'Network Voice Protocol', 'NVP-II'),
    (12, 'Xerox PUP', 'PUP'),
    (13, 'ARGUS', 'ARGUS'),
    (14, 'EMCON', 'EMCON'),
    (15, 'Cross Net Debugger', 'XNET'),
    (16, 'Chaos', 'CHAOS'),
    (17, 'User Datagram Protocol', 'UDP'),
    (18, 'Multiplexing', 'MUX'),
    (19, 'DCN Measurement Subsystems', 'DCN-MEAS'),
    (20, 'Host Monitoring Protocol', 'HMP'),
    (21, 'Packet Radio Measurement', 'PRM'),
    (22, 'XEROX NS IDP', 'XNS-IDP'),
    (23, 'Trunk-1', 'TRUNK-1'),
    (24, 'Trunk-2', 'TRUNK-2'),
    (25, 'Leaf-1', 'LEAF-1'),
    (26, 'Leaf-2', 'LEAF-2'),
    (27, 'Reliable Data Protocol', 'RDP'),
    (28, 'Internet Reliable Transaction Protocol', 'IRTP'),
    (29, 'ISO Transport Protocol Class 4', 'ISO-TP4'),
    (30, 'Bulk Data Transfer Protocol', 'NETBLT'),
    (31, 'MFE Network Services Protocol', 'MFE-NSP'),
    (32, 'MERIT Internodal Protocol', 'MERIT-INP'),
    (33, 'Datagram Congestion Control Protocol', 'DCCP'),
    (34, 'Third Party Connect Protocol', '3PC'),
    (35, 'Inter-Domain Policy Routing Protocol', 'IDPR'),
    (36, 'Xpress Transport Protocol', 'XTP'),
    (37, 'Datagram Delivery Protocol', 'DDP'),
    (38, 'IDPR Control Message Transport Protocol', 'IDPR-CMTP'),
    (39, 'TP++ Transport Protocol', 'TP++'),
    (40, 'IL Transport Protocol', 'IL'),
    (41, 'IPv6 Encapsulation (6to4 and 6in4)', 'IPv6'),
    (42, 'Source Demand Routing Protocol', 'SDRP'),
    (43, 'Routing Header for IPv6', 'IPv6-Route'),
    (44, 'Fragment Header for IPv6', 'IPv6-Frag'),
    (45, 'Inter-Domain Routing Protocol', 'IDRP'),
    (46, 'Resource Reservation Protocol', 'RSVP'),
    (47, 'Generic Routing Encapsulation', 'GRE'),
    (48, 'Dynamic Source Routing Protocol', 'DSR'),
    (49, 'Burroughs Network Architecture', 'BNA'),
    (50, 'Encapsulating Security Payload', 'ESP'),
    (51, 'Authentication Header', 'AH'),
    (52, 'Integrated Net Layer Security Protocol', 'I-NLSP'),
    (53, 'SwIPe', 'SwIPe'),
    (54, 'NBMA Address Resolution Protocol', 'NARP'),
    (55, 'IP Mobility (Min Encap)', 'MOBILE'),
    (56, 'Transport Layer Security Protocol (using Kryptonet key management)', 'TLSP'),
    (57, 'Simple Key-Management for Internet Protocol', 'SKIP'),
    (58, 'ICMP for IPv6', 'IPv6-ICMP'),
    (59, 'No Next Header for IPv6', 'IPv6-NoNxt'),
    (60, 'Destination Options for IPv6', 'IPv6-Opts'),
    (61, 'Any host internal protocol', ''),
    (62, 'CFTP', 'CFTP'),
    (63, 'Any local network', ''),
    (64, 'SATNET and Backroom EXPAK', 'SAT-EXPAK'),
    (65, 'Kryptolan', 'KRYPTOLAN'),
    (66, 'MIT Remote Virtual Disk Protocol', 'RVD'),
    (67, 'Internet Pluribus Packet Core', 'IPPC'),
    (68, 'Any distributed file system', ''),
    (69, 'SATNET Monitoring', 'SAT-MON'),
    (70, 'VISA Protocol', 'VISA'),
    (71, 'Internet Packet Core Utility', 'IPCU'),
    (72, 'Computer Protocol Network Executive', 'CPNX'),
    (73, 'Computer Protocol Heart Beat', 'CPHB'),
    (74, 'Wang Span Network', 'WSN'),
    (75, 'Packet Video Protocol', 'PVP'),
    (76, 'Backroom SATNET Monitoring', 'BR-SAT-MON'),
    (77, 'SUN ND PROTOCOL-Temporary', 'SUN-ND'),
    (78, 'WIDEBAND Monitoring', 'WB-MON'),
    (79, 'WIDEBAND EXPAK', 'WB-EXPAK'),
    (80, 'International Organization for Standardization Internet Protocol', 'ISO-IP'),
    (81, 'Versatile Message Transaction Protocol', 'VMTP'),
    (82, 'Secure Versatile Message Transaction Protocol', 'SECURE-VMTP'),
    (83, 'VINES', 'VINES'),
    --(84, 'TTP (Transaction Transport Protocol) (obsoleted March 2023)', 'TTP'),
    (84, 'Internet Protocol Traffic Manager', 'IPTM'),
    (85, 'NSFNET-IGP', 'NSFNET-IGP'),
    (86, 'Dissimilar Gateway Protocol', 'DGP'),
    (87, 'TCF', 'TCF'),
    (88, 'EIGRP', 'EIGRP'),
    (89, 'Open Shortest Path First', 'OSPF'),
    (90, 'Sprite RPC Protocol', 'Sprite-RPC'),
    (91, 'Locus Address Resolution Protocol', 'LARP'),
    (92, 'Multicast Transport Protocol', 'MTP'),
    (93, 'AX.25', 'AX.25'),
    (94, 'KA9Q NOS compatible IP over IP tunneling', 'OS'),
    (95, 'Mobile Internetworking Control Protocol', 'MICP'),
    (96, 'Semaphore Communications Sec. Pro', 'SCC-SP'),
    (97, 'Ethernet-within-IP Encapsulation', 'ETHERIP'),
    (98, 'Encapsulation Header', 'ENCAP'),
    (99, 'Any private encryption scheme', ''),
    (100, 'GMTP', 'GMTP'),
    (101, 'Ipsilon Flow Management Protocol', 'IFMP'),
    (102, 'PNNI over IP', 'PNNI'),
    (103, 'Protocol Independent Multicast', 'PIM'),
    (104, 'IBMs ARIS (Aggregate Route IP Switching) Protocol', 'ARIS'),
    (105, 'SCPS (Space Communications Protocol Standards)', 'SCPS'),
    (106, 'QNX', 'QNX'),
    (107, 'Active Networks', 'A/N'),
    (108, 'IP Payload Compression Protocol', 'IPComp'),
    (109, 'Sitara Networks Protocol', 'SNP'),
    (110, 'Compaq Peer Protocol', 'Compaq-Peer'),
    (111, 'IPX in IP', 'IPX-in-IP'),
    (112, 'Virtual Router Redundancy Protocol, Common Address Redundancy Protocol (not IANA assigned)', 'VRRP'),
    (113, 'PGM Reliable Transport Protocol', 'PGM'),
    (114, 'Any 0-hop protocol', ''),
    (115, 'Layer Two Tunneling Protocol Version 3', 'L2TP'),
    (116, 'D-II Data Exchange (DDX)', 'DDX'),
    (117, 'Interactive Agent Transfer Protocol', 'IATP'),
    (118, 'Schedule Transfer Protocol', 'STP'),
    (119, 'SpectraLink Radio Protocol', 'SRP'),
    (120, 'Universal Transport Interface Protocol', 'UTI'),
    (121, 'Simple Message Protocol', 'SMP'),
    (122, 'Simple Multicast Protocol', 'SM'),
    (123, 'Performance Transparency Protocol', 'PTP'),
    (124, 'Intermediate System to Intermediate System (IS-IS) Protocol over IPv4', 'IS-IS over IPv4'),
    (125, 'Flexible Intra-AS Routing Environment', 'FIRE'),
    (126, 'Combat Radio Transport Protocol', 'CRTP'),
    (127, 'Combat Radio User Datagram', 'CRUDP'),
    (128, 'Service-Specific Connection-Oriented Protocol in a Multilink and Connectionless Environment', 'SSCOPMCE'),
    (129, 'IPLT', ''),
    (130, 'Secure Packet Shield', 'SPS'),
    (131, 'Private IP Encapsulation within IP', 'PIPE'),
    (132, 'Stream Control Transmission Protocol', 'SCTP'),
    (133, 'Fibre Channel', 'FC'),
    (134, 'Reservation Protocol (RSVP) End-to-End Ignore', 'RSVP-E2E-IGNORE'),
    (135, 'Mobility Extension Header for IPv6', 'Mobility Header'),
    (136, 'Lightweight User Datagram Protocol', 'UDPLite'),
    (137, 'Multiprotocol Label Switching Encapsulated in IP', 'MPLS-in-IP'),
    (138, 'MANET Protocols', 'manet'),
    (139, 'Host Identity Protocol', 'HIP'),
    (140, 'Site Multihoming by IPv6 Intermediation', 'Shim6'),
    (141, 'Wrapped Encapsulating Security Payload', 'WESP'),
    (142, 'Robust Header Compression', 'ROHC'),
    (143, 'Segment Routing over IPv6', 'Ethernet'),
    (144, 'AGGFRAG Encapsulation Payload for ESP', 'AGGFRAG'),
    (145, 'Network Service Header', 'NSH'),
    (146, 'Unassigned', ''),
    (147, 'Unassigned', ''),
    (148, 'Unassigned', ''),
    (149, 'Unassigned', ''),
    (150, 'Unassigned', ''),
    (151, 'Unassigned', ''),
    (152, 'Unassigned', ''),
    (153, 'Unassigned', ''),
    (154, 'Unassigned', ''),
    (155, 'Unassigned', ''),
    (156, 'Unassigned', ''),
    (157, 'Unassigned', ''),
    (158, 'Unassigned', ''),
    (159, 'Unassigned', ''),
    (160, 'Unassigned', ''),
    (161, 'Unassigned', ''),
    (162, 'Unassigned', ''),
    (163, 'Unassigned', ''),
    (164, 'Unassigned', ''),
    (165, 'Unassigned', ''),
    (166, 'Unassigned', ''),
    (167, 'Unassigned', ''),
    (168, 'Unassigned', ''),
    (169, 'Unassigned', ''),
    (170, 'Unassigned', ''),
    (171, 'Unassigned', ''),
    (172, 'Unassigned', ''),
    (173, 'Unassigned', ''),
    (174, 'Unassigned', ''),
    (175, 'Unassigned', ''),
    (176, 'Unassigned', ''),
    (177, 'Unassigned', ''),
    (178, 'Unassigned', ''),
    (179, 'Unassigned', ''),
    (180, 'Unassigned', ''),
    (181, 'Unassigned', ''),
    (182, 'Unassigned', ''),
    (183, 'Unassigned', ''),
    (184, 'Unassigned', ''),
    (185, 'Unassigned', ''),
    (186, 'Unassigned', ''),
    (187, 'Unassigned', ''),
    (188, 'Unassigned', ''),
    (189, 'Unassigned', ''),
    (190, 'Unassigned', ''),
    (191, 'Unassigned', ''),
    (192, 'Unassigned', ''),
    (193, 'Unassigned', ''),
    (194, 'Unassigned', ''),
    (195, 'Unassigned', ''),
    (196, 'Unassigned', ''),
    (197, 'Unassigned', ''),
    (198, 'Unassigned', ''),
    (199, 'Unassigned', ''),
    (200, 'Unassigned', ''),
    (201, 'Unassigned', ''),
    (202, 'Unassigned', ''),
    (203, 'Unassigned', ''),
    (204, 'Unassigned', ''),
    (205, 'Unassigned', ''),
    (206, 'Unassigned', ''),
    (207, 'Unassigned', ''),
    (208, 'Unassigned', ''),
    (209, 'Unassigned', ''),
    (210, 'Unassigned', ''),
    (211, 'Unassigned', ''),
    (212, 'Unassigned', ''),
    (213, 'Unassigned', ''),
    (214, 'Unassigned', ''),
    (215, 'Unassigned', ''),
    (216, 'Unassigned', ''),
    (217, 'Unassigned', ''),
    (218, 'Unassigned', ''),
    (219, 'Unassigned', ''),
    (220, 'Unassigned', ''),
    (221, 'Unassigned', ''),
    (222, 'Unassigned', ''),
    (223, 'Unassigned', ''),
    (224, 'Unassigned', ''),
    (225, 'Unassigned', ''),
    (226, 'Unassigned', ''),
    (227, 'Unassigned', ''),
    (228, 'Unassigned', ''),
    (229, 'Unassigned', ''),
    (230, 'Unassigned', ''),
    (231, 'Unassigned', ''),
    (232, 'Unassigned', ''),
    (233, 'Unassigned', ''),
    (234, 'Unassigned', ''),
    (235, 'Unassigned', ''),
    (236, 'Unassigned', ''),
    (237, 'Unassigned', ''),
    (238, 'Unassigned', ''),
    (239, 'Unassigned', ''),
    (240, 'Unassigned', ''),
    (241, 'Unassigned', ''),
    (242, 'Unassigned', ''),
    (243, 'Unassigned', ''),
    (244, 'Unassigned', ''),
    (245, 'Unassigned', ''),
    (246, 'Unassigned', ''),
    (247, 'Unassigned', ''),
    (248, 'Unassigned', ''),
    (249, 'Unassigned', ''),
    (250, 'Unassigned', ''),
    (251, 'Unassigned', ''),
    (252, 'Unassigned', ''),
    (253, 'Use for experimentation and testing', 'Testing'),
    (254, 'Use for experimentation and testing', 'Testing'),
    (255, 'Reserved', '')
GO